### ISSUE TITLE
What about CV column?

### ISSUE THREAD

**Issue by ljgarcia** [BioSchemas/map2model#27]
I do not see anything on the CV column, even when mappings do have something there. Will it be included? I would say CV is very important in Bioschemas, even more now with the changes on PhysicalEntity and Record.

Cheers,

**Comment by guicalman** [comment]
Very good question! This question is related with mapping generation and partially to map2model, but I give a better description here.

If you access [spec_process_detail.md](https://github.com/BioSchemas/map2model/blob/master/spec_process_detail.md) you find the step-by-step process of how to fill the specification mapping, there is the following explanation. Maybe this was not so clear due to the building state of this file.

**CV** means Controlled Vocabulary, this field contains a list term/ontology. A term is just a text that represent the value expected and an ontology is a namespace that contains ontology name colon (:) the ontology URL.

Examples:

## Term list
term1, term2, ter3

## Ontology list
onto1: http://onto1.com, onto2: http: //onto2.com, onto3: http://onto1.com

## Mixed list

onto1: http://onto1.com, **term1**, onto2: http: //onto2.com, **term2**, **term3**, onto3: http://onto1.com

In the current version of [PhysicalEntity](http://bioschemas.org/bsc_specs/PhysicalEntity/specification/) you can see how the text of CV for 
additionalType is parsed.

Let me know if you have any additional question, or I can mark this **issue as closed**.

**Comment by ljgarcia** [comment]
This way would probably work for profiles but not necessarily for types. For instance, CV are recommended for the additionalType but which ontologies and which terms is up to the profiles, not the types. Also, CV are recommended for the additionalProperty property but which ontologies and terms depends on the property/relation that you want to describe.

**Comment by guicalman** [comment]
Thanks @ljgarcia for your feedback, but again, this is a **mapping concern** and not a map2model issue. For the community's sake, here is what I'd found about your question.

From my stand point, this is a conceptual definition misunderstanding. Reviewing the [Bioschemas Agreement Meeting's memories](https://docs.google.com/document/d/1dVxYuGT-5wwPI_bo8mqP3jhmDU7jRdxePNMlb5N6akY/edit?usp=sharing) there is no precise definition of what a Type is and what a Profile is. The concept Profile is only mentioned in two cases: 
1. _"Start with the protein **profile** using biologicalEntity"_ . Considering **Protein and BiologicalEntity** terms are mentioned, this could be your proposal. 
1. _"Alasdair made the analogy to the HCLS community **profile** (see image below) where the data repository is capturing the Summary Level description and the dataset is capturing the version level description."_

I copy @rajido and @AlasdairGray to check this discussion, maybe they have some ideas to help us clarifying this topic.

Could you please describe what do you have in mind as a Type and what as a Profile? With this concepts Bioschemas mapping spreadsheet  can be changed to fill your needs. 

>If my documentation's digging was complete, this could be a topic to be considered in the next [Bioschemas meeting](http://bioschemas.org/meetings/2017-10_AdoptionMeeting/)

**Comment by AlasdairGray** [comment]
I believe that we are now distinguishing between _types_ that need to be added to Schema.org and _profiles_ that are layered over them. Bioschemas specifications represent the _profiles_ and this is what the map2model tool generates. For _types_ we should follow the standard Schema.org representation. (I think a lot of confusion comes because our profiles very often have the same name as the type, e.g. Bioschemas Dataset is a profile over the Schema.org Dataset type.)

For _types_ there is no notion of MG, CD, or CV. Instead, a type should have a place in the Schema.org hierarchy showing what they inherit and then a set of properties that they add. These properties will have a name, expected type, and a description. We should follow the same layout as the Schema.org pages, e.g. [schema:Dataset](http://schema.org/Dataset). This layout allows a user to quickly find the properties that are most specific to that type, but do not necessarily support the marking up of resources according to a community agreed profile.

For _profiles_ the display should be supporting the use case of users marking up resources according to a  community agreed set of properties. In my opinion we should have the mandatory properties grouped together, then the recommended, and finally the optional properties, as was done with the [Bioschemas Event Specification](https://docs.google.com/document/d/12O8gsOuH2qHKpis6vTHxXExraNH5XZEnoilwNgWWgaQ/edit). As these are community profiles it is appropriate to include the MG, CD, and CV columns and to have recommendations of the particular vocabularies to use.
